#!/bin/sh

if [ "$1" = "1" ]; then
	./test_program  1 50 1 50
elif [ "$1" = "2" ]; then
	./test_program  1 50 1 10
elif [ "$1" = "3" ]; then
	./test_program  1 50 1 100
elif [ "$1" = "4" ]; then
	./test_program  2 50 1 100
elif [ "$1" = "5" ]; then
	./test_program  1 50 2 25
elif [ "$1" = "6" ]; then
	./test_program  2 50 1 5
elif [ "$1" = "7" ]; then
	./test_program  2 50 1 200
fi
